version: 2

sources:
  - name: replica
    schema: replica

    tables:

      # =====================
      # LABORATORY
      # =====================

      - name: acs_lab_test
      - name: acs_lab_test_uom
      - name: acs_laboratory
      - name: acs_laboratory_request
      - name: acs_laboratory_sample_type
      - name: acs_patient_laboratory_sample
      - name: hms_patient
      - name: hms_physician
      - name: lab_bilan
      - name: lab_request
      - name: lab_test_critearea
      - name: lab_test_criteria_template
      - name: lab_test_normal_range
      - name: lab_unit
      - name: laboratory_equipements
      - name: laboratory_group
      - name: laboratory_group_line
      - name: laboratory_request_line
      - name: patient_laboratory_test
      - name: res_partner

      # =====================
      # HR
      # =====================

      - name: employee
      - name: department
      - name: position
      - name: contract
      - name: payroll
      - name: attendance
      - name: leave_request
      - name: leave
      - name: absence_declaration
      - name: absence_reason
      - name: employee_assignment
      - name: training
      - name: training_participation
      - name: loan_assignment
      - name: loan_status
      - name: candidature

      # =====================
      # SUPPLY CHAIN
      # =====================

      - name: product
      - name: customer
      - name: supplier
      - name: sales
      - name: purchase
      - name: inventory
      - name: delivery
      - name: receipt
      - name: customer_request
      - name: proforma_request
      - name: payment
      - name: payment_method
      - name: bank_transaction
      - name: cash_transaction
      - name: financial_transaction_type
      - name: inventory_transaction_type
      - name: warehouse
      - name: storage_location
      - name: bank
      - name: cash